sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: T4rdK9pH/i3n4Fp6nlXAeKl+UU8PsXPwc4tuwrL0SPRRTv3UF+syX0AXTxRume7XeRHe5PhL5hKVS/mSkEKIYkuJBB8pnXxxa+B3kyBggZVhy6jAWR9yCYuO/UognttUdyjCr4jmL4N1MnNRT6T5q2/s9dJxk9Ho29TTKMEM5qTn8CP4Yc7ZX3+F8bvrpEVa07aPyUVpPAh63Iljf9tK/qt+u9invpTEi2fm1/ZHVpCdC1p+B/aVu8vN8VlohX8HiG4X56pkCvUPsfYhwiz+cTTPYVdvZpsdq5/L64J3qWzjZJLPUpEaQiyoQ3rvrotUTFk5H5WsGr2i80x4LgO563FutQVvb4KhuoDCF4mgnGk0rcyDEZaPpgGHZo+ufSfkbIqxnN2+JxrVNC3GJVdk1KRBEn0MoCkpMXTkK0mkT1dRTilzTGjY/gKrmjL2R5/gIQSng1VSJhby+lVMvC1ELZVcB50l4lpPTlX/Uz+w+cH1yh4ipKwc8tFGrsJVunOKVXYeuo/yXQfgi298ZupuCHqQemYq4Wm3Bcw4L5xyKJfG6VaBSVZ9gydLAh886pzzSgoLjW2wL7tGRTMljLgAqGt/Pp9nnoEKELrgZnu4eoOzYDqmDKuETjDiXl43qmtcnCIR/kg0MZuf6qRy4PbsnMwJAohhApZo1w4P8KQWvQ8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/La-Tulipe-Noire_1910
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy